package com.hwm.together.greendao.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.hwm.together.greendao.entity.Chase;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig chaseDaoConfig;

    private final ChaseDao chaseDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        chaseDaoConfig = daoConfigMap.get(ChaseDao.class).clone();
        chaseDaoConfig.initIdentityScope(type);

        chaseDao = new ChaseDao(chaseDaoConfig, this);

        registerDao(Chase.class, chaseDao);
    }
    
    public void clear() {
        chaseDaoConfig.clearIdentityScope();
    }

    public ChaseDao getChaseDao() {
        return chaseDao;
    }

}
