POST http://127.0.0.1:8080/evaluate
Content-Type: application/json

{"roomId": "roomId","userId": "userId","verifiedTimes": 0}

###

###
GET http://127.0.0.1:8080/gameresult?roomId=testRoom&userId=testUser
Content-Type: application/json

###
